apiVersion: v1
kind: Service
metadata:
  name: userservice
spec:
  selector:
    app: user-service
  type: NodePort
  ports:
  - name: userservice
    port: 4000
    targetPort: 4000
    protocol: TCP